name: Set up RDP with Ngrok

on: [push, workflow_dispatch]

jobs:
  setup-rdp:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download Ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip

    - name: Extract Ngrok
      run: Expand-Archive ngrok.zip

    - name: Authenticate Ngrok
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Start Ngrok Tunnel
      run: Start-Process .\ngrok\ngrok.exe -ArgumentList "tcp 3389" -NoNewWindow

    - name: Get Ngrok URL
      run: |
        $ngrokUrl = (.\ngrok\ngrok.exe url tcp 3389).Trim()
        echo "RDP URL: $ngrokUrl"
        echo "RDP_URL=$ngrokUrl" >> $GITHUB_ENV

    - name: Output RDP Connection Details
      run: echo "Connect to RDP using the following details: Username: runneradmin, Password: P@ssw0rd, RDP URL: ${{ env.RDP_URL }}"
